# Generated by Django 4.1.1 on 2023-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name : ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email : ')),
                ('message', models.TextField(verbose_name='Your Feedback : ')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Buissness', 'Buissness'), ('Education ', 'Education '), ('News', 'News'), ('Entertainment', 'Entertainment'), ('Gaming ', 'Gaming '), ('Lifestyle and hobbies  ', 'Lifestyle and hobbies  '), ('Other', 'Other')], default='Other', max_length=500),
        ),
    ]
