# Generated by Django 4.1.1 on 2023-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_comment_blog_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Buissness', 'Buissness'), ('Education ', 'Education '), ('News', 'News'), ('Entertainment', 'Entertainment'), ('Gaming ', 'Gaming '), ('Lifestyle_and_hobbies', 'Lifestyle_and_hobbies'), ('Other', 'Other')], default='Other', max_length=500),
        ),
    ]
