# Generated by Django 4.1.1 on 2022-12-27 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name: ')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Profile Pic: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number: ')),
                ('location', models.CharField(max_length=200, verbose_name='Location: ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
